############################################################### PLANQ #########################################################
# add to list:

list = [
  ['transfer', 'channel-32'], # secret
]

############################################################### SECRET ############################################################
[[chains]]
id = 'secret-4'
rpc_addr= 'https://rpc.secret.forbole.com:443'
grpc_addr = 'https://secret-grpc.lavenderfive.com:443'
websocket_addr = 'wss://rpc.secret.forbole.com:443/websocket'
rpc_timeout = '45s'
account_prefix = 'secret'
key_name = 'relayer'
store_prefix = 'ibc'
max_tx_size = 180000
max_gas = 2000000
gas_price = { price = 0.0125, denom = 'uscrt' }
gas_multiplier = 2
clock_drift ='1000s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
memo_prefix = 'roadz | systemd'

[chains.packet_filter]
policy = 'allow'
list = [
   ['transfer', 'channel-54'], # planq
]
